Tuple2[Long,Float]
org.apache.spark.SparkException: Job aborted due to stage failure:
Failed to serialize task 660, not attempting to retry it. Exception
during serialization: java.io.NotSerializableException:
com.logimethods.nats.connector.spark.app.SparkProcessor$dataDecoder2$$an
on$1
Serialization stack:
	- object not serializable (class:
com.logimethods.nats.connector.spark.app.SparkProcessor$dataDecoder2$$an
on$1, value:
com.logimethods.nats.connector.spark.app.SparkProcessor$dataDecoder2$$an
on$1@5cf7391b)
	- field (class:
com.logimethods.connector.nats.to_spark.NatsToSparkConnector, name:
dataDecoder, type: interface java.util.function.Function)
	- object (class
com.logimethods.connector.nats.to_spark.StandardNatsToKeyValueSparkConne
ctorImpl,
com.logimethods.connector.nats.to_spark.StandardNatsToKeyValueSparkConne
ctorImpl@4b4a13b9)
	- element of array (index: 0)
	- array (class [Lorg.apache.spark.streaming.receiver.Receiver;, size 1)
	- field (class: scala.collection.mutable.WrappedArray$ofRef, name:
array, type: class [Ljava.lang.Object;)
	- object (class scala.collection.mutable.WrappedArray$ofRef,
WrappedArray(com.logimethods.connector.nats.to_spark.StandardNatsToKeyVa
lueSparkConnectorImpl@4b4a13b9))
	- writeObject data (class:
org.apache.spark.rdd.ParallelCollectionPartition)
	- object (class org.apache.spark.rdd.ParallelCollectionPartition,
org.apache.spark.rdd.ParallelCollectionPartition@68e7)
	- field (class: org.apache.spark.scheduler.ResultTask, name:
partition, type: interface org.apache.spark.Partition)
	- object (class org.apache.spark.scheduler.ResultTask, ResultTask(592,
0))
	at
org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGSc
heduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at
org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGS
cheduler.scala:1442)
	at
org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGS
cheduler.scala:1441)
	at
scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.sca
la:59)