.withDataDecoder(decoder.dataDecoder.asJava)
org.apache.spark.SparkException: Job aborted due to stage failure:
Failed to serialize task 190, not attempting to retry it. Exception
during serialization: java.io.NotSerializableException:
scala.compat.java8.functionConverterImpls.AsJavaFunction
Serialization stack:
	- object not serializable (class:
scala.compat.java8.functionConverterImpls.AsJavaFunction, value:
scala.compat.java8.functionConverterImpls.AsJavaFunction@937f978)
	- field (class:
com.logimethods.connector.nats.to_spark.NatsToSparkConnector, name:
dataDecoder, type: interface java.util.function.Function)
	- object (class
com.logimethods.connector.nats.to_spark.StandardNatsToKeyValueSparkConne
ctorImpl,
com.logimethods.connector.nats.to_spark.StandardNatsToKeyValueSparkConne
ctorImpl@1ac58fa2)
	- element of array (index: 0)
	- array (class [Lorg.apache.spark.streaming.receiver.Receiver;, size 1)
	- field (class: scala.collection.mutable.WrappedArray$ofRef, name:
array, type: class [Ljava.lang.Object;)
	- object (class scala.collection.mutable.WrappedArray$ofRef,
WrappedArray(com.logimethods.connector.nats.to_spark.StandardNatsToKeyVa
lueSparkConnectorImpl@1ac58fa2))
	- writeObject data (class:
org.apache.spark.rdd.ParallelCollectionPartition)
	- object (class org.apache.spark.rdd.ParallelCollectionPartition,
org.apache.spark.rdd.ParallelCollectionPartition@1bb5)
	- field (class: org.apache.spark.scheduler.ResultTask, name:
partition, type: interface org.apache.spark.Partition)
	- object (class org.apache.spark.scheduler.ResultTask, ResultTask(122,
0))
	at
org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGSc
heduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at
org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGS
cheduler.scala:1442)